Feature/undo redo fix
digabi/rich-text-editor pull request #519
Opened 2022-06-29 14:17 UTC by ApsiV11

Continued version of #463 

The two main issues described in #463 remain.

Now:
1. MathQuill and LaTeX are always in sync. It is possible to modify both successively. 
2. LaTeX-values of the equation are used for history.
3. If the written LaTeX is invalid the focus hops to LaTeX automatically to prevent overriding the whole equation.
4. There are buttons for undoing and redoing.
5. An error is shown if the MathQuill-field goes empty.
6. The triangle error symbol has text to clarify that the LaTeX is invalid.

Also tests have now been added.

2022-06-30 10:24 UTC, ApsiV11 commented on src/math-editor.js
> +            onLatexUpdate(e)
Aiheutta osittain bugista toimintaa undo:ssa ja redo:ssa, kun stackkiin päätyi sama latex kahteen kertaan välillä.

2022-06-30 10:30 UTC, ApsiV11 commented on test/tests.front.js
> +// eslint-disable-next-line no-unused-vars
Mun eslint ei mennyt läpi ilman tätä jonkin takia

2022-06-30 10:33 UTC, ApsiV11 commented on src/math-editor.js
> +        const latex = $latexField.val().trim()
Ilman tota trimmiä LaTeXiin jäi pelkän /-merkin kanssa ylimääräinen välilyönti. Tässä ei siis varsinaisesti ollut tarvetta käyttää sitä trimLatex()-funktiota. Taisi ehkä jopa aiheuttaa jotain ongelmaa.

2022-06-30 10:36 UTC, ApsiV11 commented on src/util.js
> +    return array[array.length - 1]
Voisi ehkä palauttaa null:in mieluummin?

2022-07-01 06:08 UTC, pejuam approved these changes

2022-07-04 09:55 UTC, pejuam commented on src/FI.js
> +        render_error: 'LaTeX-koodissa virhe',
Haluttiinko me nyt kuitenkin vain se "ei esikatselua" -virhe, koska LaTeX-virheestä ei tiedä, ellei sitä käy kysymässä serveriltä MathJax:lta?

2022-07-05 11:57 UTC, eeroan requested changes
tee vielä rebase masterin päälle ja fiksit mielellään olemassa oileviin commiteihin. pyydä apua jos tarviit gitin fixup commitien kanssa.

2022-07-05 11:57 UTC, eeroan commented on public/rich-text-editor.css
> +  left: 630px;
tässä position absolute on vähän turha. varmaan sais inline-block-tyylillä tonne sekaan. tai jos ei muuta, niin wrappais noi napit omaan absolutella  positioituun containeriin jonka sisällä ei erikseen tarttis määritellä noiden nappien paikkoja pikselin tarkkuudella

2022-07-05 11:57 UTC, eeroan commented on public/rich-text-editor.css
> +  filter: grayscale(100%)
voisko olla vaan yhteinen .rich-text-editor-button:disabled

2022-07-05 11:57 UTC, eeroan commented on public/rich-text-editor.css
> +  filter: grayscale(100%)
laittaisin vaan suoraan värikoodin

2022-07-05 11:57 UTC, eeroan commented on server/mathSvg.js
> +    <text x="25" y="16" fill="red">LaTeX-koodissa virhe / Fel i LaTeX-koden</text>
Vai oisko parempi:

Virhe LaTeX-koodissa

en oo varma

2022-07-05 11:57 UTC, eeroan commented on src/math-editor.js
> +            ? $('[data-js="mathUndo"]').prop('disabled', false)
`$('[data-js="mathUndo"]').prop('disabled', undoStack.length <= 1)`

lisäksi kakuttaisin  riville 59 `const $mathUndo = $('[data-js="mathUndo"]')`

2022-07-05 11:57 UTC, eeroan commented on src/math-editor.js
> +            ? $('[data-js="mathRedo"]').prop('disabled', false)
tässä samat pointit kuin yllä

2022-07-05 11:57 UTC, eeroan commented on src/math-editor.js
> +        undoRedo !== 0 && mqInstance.latex().length === 0 && latex.length > 0 && $latexField.focus()
vaikka enemmän koodia, niin tää olis mun mielestä luettavampi:
```
if (undoRedo !== 0 && mqInstance.latex().length === 0 && latex.length > 0) {
  $latexField.focus()
}
```

2022-07-05 11:57 UTC, eeroan commented on src/math-editor.js
> +        $renderError.text('')
$renderError.empty()

2022-07-05 11:57 UTC, eeroan commented on test/tests.front.js
> +        })
tosi hyvä että teit myös testit

2022-07-06 09:04 UTC, merged